apiVersion: v1
kind: Template
metadata:
  name: drupal-persistent
  annotations:
    openshift.io/display-name: Drupal + MySQL (Persistent)
    description: |-
      An example Drupal application with a MySQL database.
    tags: instant-app,php,drupal,cms
    iconClass: icon-drupal
message: |-
  The following service(s) have been created in your project: ${NAME}, ${DATABASE_SERVICE_NAME}.
labels:
  template: drupal-persistent
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: drupal-openshift
    name: drupal-openshift
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: drupal-openshift:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: openshift
        uri: https://github.com/tobru/drupal-openshift.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.0
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: rmpJqoX5i-ynVoW58PpM
      type: GitHub
    - generic:
        secret: YuDYZ004aF3zgEiNdg0q
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: drupal-openshift
    name: drupal-openshift
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: drupal-mysql-data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: drupal-openshift
    name: drupal-openshift
  spec:
    replicas: 1
    selector:
      app: drupal-openshift
      deploymentconfig: drupal-openshift
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: drupal-openshift
          deploymentconfig: drupal-openshift
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: ${DATABASE_NAME}
          - name: MYSQL_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: MYSQL_USER
            value: ${DATABASE_USER}
          image: drupal-openshift
          imagePullPolicy: Always
          name: drupal-openshift
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
          - name: MYSQL_DATABASE
            value: ${DATABASE_NAME}
          - name: MYSQL_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: MYSQL_USER
            value: ${DATABASE_USER}
          image: mysql-57-rhel7
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: mysql-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mysql-volume-1
          persistentVolumeClaim:
            claimName: drupal-mysql-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - drupal-openshift
        from:
          kind: ImageStreamTag
          name: drupal-openshift:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.7
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: drupal-openshift
    name: drupal-openshift
  spec:
    port:
      targetPort: 3306-tcp
    to:
      kind: Service
      name: drupal-openshift
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: drupal-openshift
    name: drupal-openshift
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: drupal-openshift
      deploymentconfig: drupal-openshift
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: DATABASE_NAME
  description: Database name
  value: drupal
- name: DATABASE_USER
  description: Database user name
  value: drupal
- name: DATABASE_PASSWORD
  description: Database user password
  generate: expression
  from: "[a-zA-Z0-9]{16}"
