apiVersion: v1
kind: Template
metadata:
  name: nexus-persistent
labels:
  template: nexus-persistent
  group: ci
metadata:
  annotations:
    description: Creates a persistent Nexus Repository
    tags: instant-app,nexus,ci
  name: nexus-persistent
parameters:
- description: Nexus Repository service name
  name: NEXUS_SERVICE_NAME
  value: nexus
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: nexus-data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Sonatype Nexus repository manager's http port
    labels:
      app: ${NEXUS_SERVICE_NAME}
    name: ${NEXUS_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: ${NEXUS_SERVICE_NAME}
      deploymentconfig: ${NEXUS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NEXUS_SERVICE_NAME}
    name: ${NEXUS_SERVICE_NAME}
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: ${NEXUS_SERVICE_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    tags:
    - annotations:
        description: The Nexus Docker image
        tags: nexus
      from:
        kind: DockerImage
        name: openshiftdemos/nexus:2.13.0-01
      importPolicy: {}
      name: "2.13.0-01"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NEXUS_SERVICE_NAME}
    name: ${NEXUS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${NEXUS_SERVICE_NAME}
      deploymentconfig: ${NEXUS_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${NEXUS_SERVICE_NAME}
          deploymentconfig: ${NEXUS_SERVICE_NAME}
      spec:
        containers:
        - image: " "
          imagePullPolicy: Always
          name: nexus
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/nexus-work
            name: ${NEXUS_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${NEXUS_SERVICE_NAME}-data
          persistentVolumeClaim:
            claimName: nexus-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NEXUS_SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: nexus:2.13.0-01
      type: ImageChange
  status: {}
