kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Jenkins pipeline template for git-hosted jenkinsfile
    tags: instant-app,jenkins,jenkinsfile,git
  name: jenkins-pipeline-git
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
  name: ${PIPELINE_NAME}
  labels:
      name: ${PIPELINE_NAME}
  annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "app-node", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    triggers:
      - type: GitHub
        github:
          secret: ${GITHUB_SECRET}
      - type: Generic
        generic:
          secret: ${GENERIC_SECRET}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_PIPELINE_URL}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: >
          node("nodejs"){
          
          }
      type: JenkinsPipeline
  output: {}
  resources: {}
  postCommit: {}
parameters:
- description: Jenkins pipeline name
  name: PIPELINE_NAME
  value: my-pipeline
- description: Github secret value
  name: GITHUB_SECRET
  value: github-secret
- description: Generic secret value
  name: GENERIC_SECRET
  value: generic-secret
